# Dcard登入的帳密 記得冒號後空一格
DcardLogin:
 Account: vi000246@gmail.com
 Password: 

# 通知方式
Notify:
 PTTWater: #PTT水球
    IsEnable: True # 是否啟用
    WaterTarget: vi000246 #發送水球的目標
    Account: vscode # 發送水球的帳號
    Password:  #發送水球的密碼

 Facebook: #臉書通知
    IsEnable: False # 是否啟用
    Account: vi000246 # 臉書帳號
    Password:  # 臉書密碼

 Line: # Line Notify 參考這篇設置http://studyhost.blogspot.tw/2016/12/linebot6-botline-notify.html
    IsEnable: True
    Token: zxSeJ7zfqOcttg04N7np5GUDiebbqZvXJ6WDyhO2F6n
